/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DomainModel.ChucVu;
import DomainModel.CuaHang;
import DomainModel.HoaDon;
import DomainModel.KhachHang;
import DomainModel.NhanVien;
import Service.IManageChucVuService;
import Service.IManageCuaHangService;
import Service.IManageHoaDonService;
import Service.IManageKhachHangService;
import Service.IManageNhanVienService;
import Service.ManageChucVuService;
import Service.ManageCuaHangService;
import Service.ManageHoaDonService;
import Service.ManageKhachHangService;
import Service.ManageNhanVienService;
import ViewModels.QLCtsp;
import ViewModels.QLKhachHang;
import ViewModels.QLNv;
import ViewModels.QLhd;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Trong Hieu
 */
public class FrmHoaDon extends javax.swing.JFrame {

    DefaultTableModel dtm;
    DefaultComboBoxModel dcboKH;
    DefaultComboBoxModel dcboNV;
    List<QLhd> lstQLHD;
    int row;
    IManageNhanVienService _iManageNhanVienService;
    IManageKhachHangService _iManageKhachHangService;
    IManageHoaDonService _iManageHoaDonService;
    List<QLKhachHang> lstQLKH;
    List<QLNv> lstQLNV;

    /**
     * Creates new form FrmHoaDon
     */
    public FrmHoaDon() {
        initComponents();
        setLocationRelativeTo(null);
        _iManageNhanVienService = new ManageNhanVienService();
        _iManageHoaDonService = new ManageHoaDonService();
        _iManageKhachHangService = new ManageKhachHangService();
        dcboKH = (DefaultComboBoxModel) cboKH.getModel();
        dcboNV = (DefaultComboBoxModel) cboNV.getModel();

        lstQLKH = _iManageKhachHangService.getAll();
        lstQLNV = _iManageNhanVienService.getAll();
        for (QLKhachHang x : lstQLKH) {
            dcboKH.addElement(x.getMa());
        }
        for (QLNv x : lstQLNV) {
            dcboNV.addElement(x.getMa());
        }

        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNgayTao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNgayShip = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnADD = new javax.swing.JButton();
        txtSDT = new javax.swing.JTextField();
        btnEDIT = new javax.swing.JButton();
        btnDELETE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHD = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboKH = new javax.swing.JComboBox<>();
        cboNV = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtNgayTT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTT = new javax.swing.JTextField();
        txtTenNN = new javax.swing.JTextField();
        txtDC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("NGÀY SHIP");

        jLabel8.setText("NGÀY NHẬN");

        jLabel9.setText("SDT");

        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        btnEDIT.setText("EDIT");
        btnEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEDITActionPerformed(evt);
            }
        });

        btnDELETE.setText("DELETE");
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });

        jLabel2.setText("MA");

        jLabel3.setText("MÃ KH");

        tblHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "MÃ KHÁCH HÀNG", "MÃ NHÂN VIÊN", "MA", "NGÀY TẠO", "NGÀY THANH TOÁN", "NGÀY SHIP", "NGÀY NHẬN", "TÌNH TRẠNG", "TÊN NGƯỜI NHẬN", "ĐỊA CHỈ", "SDT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHD);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("QUẢN LÝ HÓA ĐƠN");

        jLabel4.setText("MÃ NV");

        jLabel5.setText("NGÀY TẠO");

        jLabel6.setText("NGÀY TT");

        jLabel10.setText("TÌNH TRẠNG");

        jLabel11.setText("TÊN NGƯỜI NHẬN");

        jLabel12.setText("ĐỊA CHỈ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(cboKH, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabel6)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboNV, 0, 174, Short.MAX_VALUE)
                    .addComponent(txtNgayTT))
                .addGap(450, 450, 450)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTT)
                    .addComponent(txtTenNN)
                    .addComponent(txtDC, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addContainerGap(413, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1661, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(37, 37, 37)
                                            .addComponent(btnADD)
                                            .addGap(83, 83, 83)
                                            .addComponent(btnEDIT))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3))
                                            .addGap(24, 24, 24)
                                            .addComponent(txtMa)))
                                    .addGap(79, 79, 79)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnDELETE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5))
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(79, 79, 79)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNgayShip)
                                        .addComponent(txtNN)
                                        .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(555, 555, 555)
                                    .addComponent(jLabel14)))
                            .addGap(731, 731, 731)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTenNN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNgayTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel14)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)
                        .addComponent(txtNgayShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtNN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnADD)
                        .addComponent(btnEDIT)
                        .addComponent(btnDELETE))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm ko?", "Thêm", JOptionPane.YES_NO_OPTION);
        if (hoi == JOptionPane.YES_OPTION) {
            for (int i = 0; i < lstQLHD.size(); i++) {
                if (txtMa.getText().equalsIgnoreCase(lstQLHD.get(i).getMa())) {
                    JOptionPane.showMessageDialog(this, "Mã sản phẩm bị trùng");
                    return;
                }
            }

            try {
                JOptionPane.showMessageDialog(this, _iManageHoaDonService.add(getData()));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn lại");
            }

            loadDataToTable();
        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void btnEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEDITActionPerformed
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa?", "Sửa", JOptionPane.YES_NO_OPTION);
        if (hoi == JOptionPane.YES_OPTION) {
            for (int i = 0; i < lstQLHD.size(); i++) {
                if (row != i && lstQLHD.get(i).getMa().equalsIgnoreCase(txtMa.getText())) {
                    JOptionPane.showMessageDialog(this, "Mã đã tồn tại");
                    return;
                }
            }

            try {
                JOptionPane.showMessageDialog(this, _iManageHoaDonService.edit(getID(), getData()));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Mời chọn lại");
            }

            loadDataToTable();
        }
    }//GEN-LAST:event_btnEDITActionPerformed

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa?", "Xóa", JOptionPane.YES_NO_OPTION);
        if (hoi == JOptionPane.YES_OPTION) {
            try {
                JOptionPane.showMessageDialog(this, _iManageHoaDonService.delete(getID()));
                loadDataToTable();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Mời chọn lại");
            }

        }
    }//GEN-LAST:event_btnDELETEActionPerformed

    private void tblHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHDMouseClicked
        row = tblHD.getSelectedRow();
        if (row == -1) {
            return;
        }
        dcboKH.setSelectedItem(tblHD.getValueAt(row, 1));
        dcboNV.setSelectedItem(tblHD.getValueAt(row, 2));
        txtMa.setText(tblHD.getValueAt(row, 3).toString());
        txtNgayTao.setText(tblHD.getValueAt(row, 4).toString());
        txtNgayTT.setText(tblHD.getValueAt(row, 5).toString());
        txtNgayShip.setText(tblHD.getValueAt(row, 6).toString());
        txtNN.setText(tblHD.getValueAt(row, 7).toString());
        txtTT.setText(tblHD.getValueAt(row, 8).toString());
        txtTenNN.setText(tblHD.getValueAt(row, 9).toString());
        txtDC.setText(tblHD.getValueAt(row, 10).toString());
        txtSDT.setText(tblHD.getValueAt(row, 11).toString());

    }//GEN-LAST:event_tblHDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnEDIT;
    private javax.swing.JComboBox<String> cboKH;
    private javax.swing.JComboBox<String> cboNV;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHD;
    private javax.swing.JTextField txtDC;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNN;
    private javax.swing.JTextField txtNgayShip;
    private javax.swing.JTextField txtNgayTT;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTT;
    private javax.swing.JTextField txtTenNN;
    // End of variables declaration//GEN-END:variables

    private void loadDataToTable() {
        dtm = (DefaultTableModel) tblHD.getModel();
        lstQLHD = _iManageHoaDonService.getAll();
        dtm.setRowCount(0);
        int count = 1;
        for (QLhd x : lstQLHD) {
            dtm.addRow(new Object[]{count, _iManageKhachHangService.getById(x.getIdkh()).getMa(), _iManageNhanVienService.getNVById(x.getIdnv()).getMa(), x.getMa(), x.getNgaytao(), x.getNgaythanhtoan(), x.getNgayship(), x.getNgaynhan(), x.getTinhtrang(), x.getTennguoinhan(), x.getDiachi(), x.getSdt()});
            count++;
        }

    }

//    private HoaDon getHDFromInput() throws ParseException {
//        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
//
//        Date dateNT = date.parse(txtNgayTao.getText());
//        Date dateTT = date.parse(txtNgayTT.getText());
//        Date dateSHIP = date.parse(txtNgayShip.getText());
//        Date dateNHAN = date.parse(txtNN.getText());
//
//        return new HoaDon(txtID.getText(), lstKH.get(cboKH.getSelectedIndex()).getId(), lstNV.get(cboNV.getSelectedIndex()).getId(), txtMa.getText(), dateNT, dateTT, dateSHIP, dateNHAN, Integer.parseInt(txtTT.getText()), txtTenNN.getText(), txtDC.getText(), txtSDT.getText());
//    }
    private QLhd getData() throws ParseException {

        DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Date dateNT = format.parse(txtNgayTao.getText());
        Date dateNTT = format.parse(txtNgayTT.getText());
        Date dateNS = format.parse(txtNgayShip.getText());
        Date dateNN = format.parse(txtNgayShip.getText());
        int ikh = cboKH.getSelectedIndex();
        int inv = cboNV.getSelectedIndex();
        return new QLhd(lstQLKH.get(ikh).getId(), lstQLNV.get(inv).getId(), txtMa.getText(), dateNT, dateNTT, dateNS, dateNN, Integer.parseInt(txtTT.getText()), txtTenNN.getText(), txtDC.getText(), txtSDT.getText());
    }

    private String getID() {
        int index = tblHD.getSelectedRow();
        return lstQLHD.get(index).getId();
    }
}
